name: pricing hacker
# baseurl: /solar-theme-jekyll
description: "Growth Marketing and Pricing Strategy: Looking Under The Hood"



gems: [jekyll-paginate]

permalink: /:year/:month/:day/:title/
paginate: 5
highlighter: rouge

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']
